### ISSUE TITLE
Maps

### ISSUE THREAD

**Issue by JavaEE-Dev** [OvercastNetwork/ProjectAres#4]
Are we going to have a maps repo?

**Comment by CoWinkKeyDinkInc** [comment]
Here is two map repos for now.

https://github.com/CoWinkKeyDinkInc/CardinalPGM-Maps

https://mcresourcepile.github.io/mapstack/overcast

**Comment by Pablete1234** [comment]
OvercastNetwork does not own the maps, they are the map author's work, they are the ones that need to decide if they want to have their maps publicly available, Map Stack is a public place for authors to put their maps on if they wish to, so that's what you should use:
[Website](https://mcresourcepile.github.io/mapstack/overcast)  [Github repo] (https://github.com/MCResourcePile/overcast-maps)
